-- MySQL Script generated by MySQL Workbench
-- Mon Jan 15 22:05:11 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sportsportal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sportsportal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sportsportal` DEFAULT CHARACTER SET utf8 ;
USE `sportsportal` ;

-- -----------------------------------------------------
-- Table `sportsportal`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportsportal`.`Role` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportsportal`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportsportal`.`User` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Role_ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_User_Role1_idx` (`Role_ID` ASC),
  CONSTRAINT `fk_User_Role1`
    FOREIGN KEY (`Role_ID`)
    REFERENCES `sportsportal`.`Role` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportsportal`.`Playground`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportsportal`.`Playground` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportsportal`.`Sport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportsportal`.`Sport` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportsportal`.`UserSpecialization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportsportal`.`UserSpecialization` (
  `User_ID` INT NOT NULL,
  `Sport_ID` INT NOT NULL,
  PRIMARY KEY (`User_ID`, `Sport_ID`),
  INDEX `fk_User_has_Sport_Sport1_idx` (`Sport_ID` ASC),
  INDEX `fk_User_has_Sport_User1_idx` (`User_ID` ASC),
  CONSTRAINT `fk_User_has_Sport_User1`
    FOREIGN KEY (`User_ID`)
    REFERENCES `sportsportal`.`User` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Sport_Sport1`
    FOREIGN KEY (`Sport_ID`)
    REFERENCES `sportsportal`.`Sport` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportsportal`.`PlaygroundSpecialization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportsportal`.`PlaygroundSpecialization` (
  `Playground_ID` INT NOT NULL,
  `Sport_ID` INT NOT NULL,
  PRIMARY KEY (`Playground_ID`, `Sport_ID`),
  INDEX `fk_Playground_has_Sport_Sport1_idx` (`Sport_ID` ASC),
  INDEX `fk_Playground_has_Sport_Playground1_idx` (`Playground_ID` ASC),
  CONSTRAINT `fk_Playground_has_Sport_Playground1`
    FOREIGN KEY (`Playground_ID`)
    REFERENCES `sportsportal`.`Playground` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Playground_has_Sport_Sport1`
    FOREIGN KEY (`Sport_ID`)
    REFERENCES `sportsportal`.`Sport` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportsportal`.`Team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportsportal`.`Team` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Captain_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Team_User1_idx` (`Captain_ID` ASC),
  CONSTRAINT `fk_Team_User1`
    FOREIGN KEY (`Captain_ID`)
    REFERENCES `sportsportal`.`User` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportsportal`.`Layout`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportsportal`.`Layout` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Sport_ID` INT NOT NULL,
  `Capacity` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Layout_Sport1_idx` (`Sport_ID` ASC),
  CONSTRAINT `fk_Layout_Sport1`
    FOREIGN KEY (`Sport_ID`)
    REFERENCES `sportsportal`.`Sport` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportsportal`.`Booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportsportal`.`Booking` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Playground_ID` INT NOT NULL,
  `Partial` TINYINT NOT NULL DEFAULT 0,
  `EventTime` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Booking_Playground1_idx` (`Playground_ID` ASC),
  CONSTRAINT `fk_Booking_Playground1`
    FOREIGN KEY (`Playground_ID`)
    REFERENCES `sportsportal`.`Playground` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportsportal`.`Match`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportsportal`.`Match` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Creator_ID` INT NOT NULL,
  `Layout_ID` INT NOT NULL,
  `Comand_Red_ID` INT NOT NULL,
  `Comand_Blue_ID` INT NOT NULL,
  `Booking_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Match_Comand1_idx` (`Comand_Red_ID` ASC),
  INDEX `fk_Match_Comand2_idx` (`Comand_Blue_ID` ASC),
  INDEX `fk_Match_Layout1_idx` (`Layout_ID` ASC),
  INDEX `fk_Match_User1_idx` (`Creator_ID` ASC),
  INDEX `fk_Match_Booking1_idx` (`Booking_ID` ASC),
  CONSTRAINT `fk_Match_Comand1`
    FOREIGN KEY (`Comand_Red_ID`)
    REFERENCES `sportsportal`.`Team` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Match_Comand2`
    FOREIGN KEY (`Comand_Blue_ID`)
    REFERENCES `sportsportal`.`Team` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Match_Layout1`
    FOREIGN KEY (`Layout_ID`)
    REFERENCES `sportsportal`.`Layout` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Match_User1`
    FOREIGN KEY (`Creator_ID`)
    REFERENCES `sportsportal`.`User` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Match_Booking1`
    FOREIGN KEY (`Booking_ID`)
    REFERENCES `sportsportal`.`Booking` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportsportal`.`TeamMembership`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportsportal`.`TeamMembership` (
  `User_ID` INT NOT NULL,
  `Comand_ID` INT NOT NULL,
  `Position` INT NOT NULL,
  `Readiness` TINYINT NOT NULL,
  PRIMARY KEY (`User_ID`, `Comand_ID`),
  INDEX `fk_User_has_Comand_Comand1_idx` (`Comand_ID` ASC),
  INDEX `fk_User_has_Comand_User1_idx` (`User_ID` ASC),
  CONSTRAINT `fk_User_has_Comand_User1`
    FOREIGN KEY (`User_ID`)
    REFERENCES `sportsportal`.`User` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Comand_Comand1`
    FOREIGN KEY (`Comand_ID`)
    REFERENCES `sportsportal`.`Team` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportsportal`.`MatchResult`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportsportal`.`MatchResult` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Team_ID` INT NOT NULL,
  `Score` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Score_Team1_idx` (`Team_ID` ASC),
  CONSTRAINT `fk_Score_Team1`
    FOREIGN KEY (`Team_ID`)
    REFERENCES `sportsportal`.`Team` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportsportal`.`Lease`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportsportal`.`Lease` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Booking_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Lease_Booking1_idx` (`Booking_ID` ASC),
  CONSTRAINT `fk_Lease_Booking1`
    FOREIGN KEY (`Booking_ID`)
    REFERENCES `sportsportal`.`Booking` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sportsportal`.`Training`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sportsportal`.`Training` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Booking_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Training_Booking1_idx` (`Booking_ID` ASC),
  CONSTRAINT `fk_Training_Booking1`
    FOREIGN KEY (`Booking_ID`)
    REFERENCES `sportsportal`.`Booking` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
